services:
    app:
        image: noeldemartin/lss
        security_opt:
            - no-new-privileges:true
        volumes:
            - ./database/database.sqlite:/app/database/database.sqlite
            - ./storage:/app/storage
            - ./.env:/app/.env
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - lss

networks:
    default:
        name: nginx-agora-lss
        external: true
