server {
  listen 80;
  listen [::]:80;
  server_name lss.noeldemartin.com *.lss.noeldemartin.com;
  server_tokens off;
  root /var/www/lss/public;
  location /.well-known/acme-challenge/ { allow all; }
  location / { return 301 https://$host$request_uri; }
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  http2 on;
  server_name lss.noeldemartin.com *.lss.noeldemartin.com;
  server_tokens off;
  root /var/www/lss/public;
  index index.php;

  ssl_certificate /etc/letsencrypt/live/lss.noeldemartin.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/lss.noeldemartin.com/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!MEDIUM:!LOW:!aNULL:!NULL:!SHA;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;

  # Security headers
  add_header Strict-Transport-Security "max-age=2592000; includeSubDomains" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  add_header Permissions-Policy "interest-cohort=()" always;

  charset utf-8;
  access_log off;

  gzip on;
  gzip_disable "msie6";
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

  keepalive_timeout    70;
  sendfile             on;
  client_max_body_size 80m;

  location ~* \.(jpg|jpeg|gif|css|png|js|ico|woff2)$ {
    expires max;

    try_files $uri /index.php?$query_string;
  }

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    try_files $fastcgi_script_name =404;

    fastcgi_pass lss:9000;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /app/public/$fastcgi_script_name;
    fastcgi_hide_header X-Powered-By;

    tcp_nodelay on;
  }

}
