name: CI
on: [push]
jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: json, dom, curl, libxml, mbstring
          coverage: none
      - name: Prepare The Environment
        run: cp .env.example .env
      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Run Linting
        run: ./vendor/bin/pint --test
      - name: Run Static Analysis
        run: ./vendor/bin/phpstan analyse
      - name: Run Tests
        run: php artisan test
